### ISSUE TITLE
Error: Unknown data type found 0 at offset 48

### ISSUE THREAD

**Issue by drozdowsky** [x87/scout#10]
```
Error: Unknown data type found 0 at offset 48
at Function.error (/mnt/d/__download_linux/scout.js/build/scout.js:17492:16)
    at definition.params.forEach.opcodeParam (/mnt/d/__download_linux/scout.js/build/scout.js:19836:37)
    at Array.forEach (<anonymous>)
    at Parser.getInstructionParams (/mnt/d/__download_linux/scout.js/build/scout.js:19825:27)
    at Parser.getInstruction (/mnt/d/__download_linux/scout.js/build/scout.js:19812:26)
    at Object.next (/mnt/d/__download_linux/scout.js/build/scout.js:19697:33)
    at Parser.getInstructions (/mnt/d/__download_linux/scout.js/build/scout.js:19683:20)
    at Parser.parse (/mnt/d/__download_linux/scout.js/build/scout.js:19667:38)
    at Object.<anonymous> (/mnt/d/__download_linux/scout.js/build/scout.js:152:38)
    at Generator.next (<anonymous>)

```

What I did:
npm install
npm run build
node opcodes > build/gta3.json
cd build
node scout < main.scm -g vc -p > out.txt       # throw here

I use main.scm from VC - Japanese Version

Thanks for the tool btw :)

**Comment by x87** [comment]
I haven't tried yet, but you can't decompile Vice City SCM with GTA3 opcode definitions. You have to run 
```
node opcodes gtavc.ini > build/gtavc.json
```

**Comment by droso11** [comment]
Thanks for reply
Error: Unknown data type found 0 at offset 10 now

Pretty sure that main.scm has bit different opcodes e.g. 059C which is IS_JAPANESE without parametrs (https://github.com/thelink2012/gta3sc/issues/119)
How can I debug this?
Thanks for reply

**Comment by x87** [comment]
This will be addressed in #11

**Comment by droso11** [comment]
Thanks for investing your time into this, I will checkout the branch soon

**Comment by droso11** [comment]
It works, thanks :)
